# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('project_man', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='projectman.ProjectmanagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Done', 'Realizada'), ('Delayed', 'Atrasada'), ('Process', 'En proceso'), ('Pause', 'Pausada'), ('Reject', 'Rechazada'), ('Leaved', 'Abandonada')], default='Process', max_length=15)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='projectman.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to='projectman.DeveloperProfile')),
            ],
        ),
    ]
