# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.ProjectmanagerProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
