# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
