# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_end_estimated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_end_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_start_estimated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_start_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
