# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0002_auto_20180528_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='cellphone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='github',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='projectmanagerprofile',
            name='cellphone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
