# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0002_auto_20180605_2022'),
        ('projectman', '0003_auto_20180606_1231'),
    ]

    operations = [
    ]
