# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0003_auto_20180606_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presupuesto', models.IntegerField()),
                ('Valor_HT_desarrollador', models.IntegerField()),
                ('HT_estimadas', models.IntegerField()),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.Project')),
            ],
        ),
    ]
