# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0004_informe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Presupuesto', models.FloatField()),
                ('Valor_HT_desarrollador', models.FloatField()),
                ('HT_estimadas', models.IntegerField()),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='informe',
            name='project',
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
    ]
