# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0004_merge_20180606_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position'], 'permissions': (('view_project', 'Can see projects'),)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position'], 'permissions': (('view_task', 'Can see task'), ('change_status_task', 'Can change status to task'))},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
