# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0005_auto_20180606_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
    ]
