# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0005_auto_20180606_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailbudget',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='hours_est',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_hour_dev',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='DetailBudget',
        ),
    ]
