# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0006_auto_20180606_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.Project')),
            ],
        ),
    ]
