# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0006_auto_20180606_2115'),
        ('projectman', '0006_auto_20180607_0925'),
        ('projectman', '0007_auto_20180607_1420'),
    ]

    operations = [
    ]
