# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0007_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hours_est',
            new_name='hours_estimated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='price_hour_dev',
            new_name='price_hour_developer',
        ),
    ]
