# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0002_project_task'),
        ('projectman', '0008_merge_20180607_1710'),
        ('projectman', '0006_auto_20180607_0925'),
    ]

    operations = [
    ]
