# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0008_auto_20180607_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('developer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.DeveloperProfile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'In-progess'), (3, 'To-do')], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='est_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='real_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.Task'),
        ),
    ]
