# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectman', '0009_merge_20180608_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position'], 'permissions': (('view_project', 'Can see projects'),)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position'], 'permissions': (('view_task', 'Can see task'), ('change_status_task', 'Can change status to task'))},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='finish_date',
            new_name='time_end_estimated',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='finish_date',
            new_name='estimated_target_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_man',
        ),
        migrations.RemoveField(
            model_name='task',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ManyToManyField(to='projectman.ClientProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.CharField(default='sin', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.ProjectmanagerProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.TextField(default='nn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time_end_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='time_start_estimated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='time_start_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='costs',
            field=models.BigIntegerField(default=1222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='requeriments',
            field=models.TextField(default='asdasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectman.DeveloperProfile'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'In-progess'), (3, 'To-do')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectman.Project'),
            preserve_default=False,
        ),
    ]
