# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_man',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectman.ProjectmanagerProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to='projectman.DeveloperProfile'),
        ),
    ]
