# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180530_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_man',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectman.ProjectmanagerProfile'),
        ),
    ]
