# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180530_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
