# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180530_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Realizada'), ('Delayed', 'Atrasada'), ('Process', 'En proceso'), ('Pause', 'Pausada'), ('Reject', 'Rechazada'), ('Leaved', 'Abandonada')], default='Process', max_length=15),
        ),
    ]
